### PR TITLE
Change random avatar without reloading the site

### PR DESCRIPTION
**Pull request by 7br-uno**
Issue fixes based on #8

### CODE REVIEW

**Comment by favrora** [comment]
Everything is fine, but there are a couple of mistakes. Now, when you click on the "Random avatar" button, the application can issue an avatar without eyes, eyebrows, clothes, these body parts must always be on the avatar. I think we need to fix this.

**Comment by 7br-uno** [comment]
> Everything is fine, but there are a couple of mistakes. Now, when you click on the "Random avatar" button, the application can issue an avatar without eyes, eyebrows, clothes, these body parts must always be on the avatar. I think we need to fix this.

That's true. To have a mouth is very important too 😄

**Comment by favrora** [comment]
> > Everything is fine, but there are a couple of mistakes. Now, when you click on the "Random avatar" button, the application can issue an avatar without eyes, eyebrows, clothes, these body parts must always be on the avatar. I think we need to fix this.
> 
> That's true. To have a mouth is very important too 😄

Yes, I agree. 😂

**Comment by favrora** [comment]
Everything is great now! I will add your nickname in the description of the repository and indicate that you completed this task.

Later I will make the interface of the buttons more user-friendly as they are small now.

**Comment by favrora** [comment]
Thank you!

**Comment by 7br-uno** [comment]
> Thank you!

Any time!
This is such a cool project!

**Pull request merged**
